CoolJH2K/dis-cover-music

- index.html
> outline for html done

- homepage.html
- index.html
Now to go over bulma documentation for styling
> Added bulma to both index and homepage htmls

- assets/css/style.css
- index.html
Please review changes to html and css
> header updated, css updated with project color scheme

- index.html
Please review changes to html and css
> fixed our tittle in head section

- assets/css/landingpage.css
- homepage.html
The footer still needs some work, but is still OK-ish.
> I attempted to make the footer.

- assets/css/style.css
- index.html
> added a search button to index page

- assets/css/landingpage.css
- homepage.html
> adjustments to css

- assets/css/style.css
- index.html
Please review and let me know if I need to change anything. css was also changed
> drop down added for search and genre

- assets/css/landingpage.css
- assets/css/style.css
- assets/js/homepage.js
- assets/js/script.js
- assets/js/youtube-api.js
- homepage.html
- index.html
Reverts CoolJH2K/dis-cover-music#83
> Revert "Revert "test fix""

- assets/css/style.css
- index.html
Added a footer to index.html and the footer's CSS.
> Added a footer element to index.html and the footer's CSS.

- assets/css/style.css
- index.html
> Fixed footer position/gaps

- assets/css/style.css
> fixes to css for genre

- assets/css/style.css
- index.html
> fix to div and css

- index.html
hi! I would like to be merged thanks
> fixes to spotify container

- assets/css/style.css
- index.html
> created liberties with background colors

- index.html
> updates to genre list

- assets/css/style.css
> centered go home button

- assets/css/style.css
- index.html
Option 1 css reverted colors identical styling.
> Option1css

- assets/css/style.css
Color adjustments for title text.
> adjustment of title colors

- assets/css/style.css
> css adjustments 2.0

- assets/js/script.js
- assets/js/youtube-api.js
> Fixed ratio of embeds

- assets/css/style.css
- index.html
> addition to css comments and edits, html

- assets/css/style.css
> please check ajustments to css

- assets/css/landingpage.css
> comments added to page

- assets/css/landingpage.css
- assets/css/style.css
> Mediaqueries
